#!/bin/bash
set -ex

ROOT_DIR=$(git rev-parse --show-toplevel)
DOCKER_NAME_POSTFIX=-$(basename $(dirname $ROOT_DIR))
DOCKER=ZDEV"$DOCKER_NAME_POSTFIX"

[[ -z "$DOCKER" ]] && echo "ERROR: no running container found" && exit 1


docker exec --user $USER $DOCKER $@
