#!/bin/bash

git_dir=$(git rev-parse --show-toplevel)
echo "Building ZEUS..."
make -C "$git_dir"/visual_odometry/cpp/build -j5 > /dev/null
echo "..done"

PYTHONPATH="$git_dir"/visual_odometry python3 $@
